server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/register_adm_db

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672}
spring.rabbitmq.ssl.enabled=${SPRING_RABBITMQ_SSL_ENABLED:false}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
